<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCR0A037\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCR0A037/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCR0A037.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCR0A037\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCR0A037\App_KernelDevDebugContainer([
    'container.build_hash' => 'CR0A037',
    'container.build_id' => '5ef45cdf',
    'container.build_time' => 1706103413,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCR0A037');
