<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], [], []],
    '_profiler_xdebug' => [[], ['_controller' => 'web_profiler.controller.profiler::xdebugAction'], [], [['text', '/_profiler/xdebug']], [], [], []],
    '_profiler_font' => [['fontName'], ['_controller' => 'web_profiler.controller.profiler::fontAction'], [], [['text', '.woff2'], ['variable', '/', '[^/\\.]++', 'fontName', true], ['text', '/_profiler/font']], [], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\JbarbierController::index'], [], [['text', '/']], [], [], []],
    'about' => [[], ['_controller' => 'App\\Controller\\JbarbierController::about'], [], [['text', '/about']], [], [], []],
    'cv' => [[], ['_controller' => 'App\\Controller\\JbarbierController::resume'], [], [['text', '/cv']], [], [], []],
    'portfolio' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolio'], [], [['text', '/portfolio']], [], [], []],
    'portfolioconnecter' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolioconnecter'], [], [['text', '/portfolioconnecter']], [], [], []],
    'portfolioprogrammer' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolioprogrammer'], [], [['text', '/portfolioprogrammer']], [], [], []],
    'portfolioadministrer' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolioadministrer'], [], [['text', '/portfolioadministrer']], [], [], []],
    'App\Controller\JbarbierController::index' => [[], ['_controller' => 'App\\Controller\\JbarbierController::index'], [], [['text', '/']], [], [], []],
    'App\Controller\JbarbierController::about' => [[], ['_controller' => 'App\\Controller\\JbarbierController::about'], [], [['text', '/about']], [], [], []],
    'App\Controller\JbarbierController::resume' => [[], ['_controller' => 'App\\Controller\\JbarbierController::resume'], [], [['text', '/cv']], [], [], []],
    'App\Controller\JbarbierController::portfolio' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolio'], [], [['text', '/portfolio']], [], [], []],
    'App\Controller\JbarbierController::portfolioconnecter' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolioconnecter'], [], [['text', '/portfolioconnecter']], [], [], []],
    'App\Controller\JbarbierController::portfolioprogrammer' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolioprogrammer'], [], [['text', '/portfolioprogrammer']], [], [], []],
    'App\Controller\JbarbierController::portfolioadministrer' => [[], ['_controller' => 'App\\Controller\\JbarbierController::portfolioadministrer'], [], [['text', '/portfolioadministrer']], [], [], []],
];
